# Generated by Django 3.0 on 2021-05-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('password', models.CharField(max_length=20, verbose_name='password')),
                ('birthday', models.CharField(max_length=20, verbose_name='birthday')),
                ('telephone', models.CharField(max_length=11, verbose_name='telephone')),
                ('status', models.BooleanField(default=False, verbose_name='status')),
            ],
        ),
    ]
