# Generated by Django 3.0 on 2021-05-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_socket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatrecord',
            name='record',
        ),
        migrations.AddField(
            model_name='chatrecord',
            name='text',
            field=models.CharField(default=1, max_length=100, verbose_name='text'),
            preserve_default=False,
        ),
    ]
